from pathlib import Path
from PIL import Image, ImageEnhance

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "launcher_art.h"
SIZE = (320, 200)
LOGOS = [
    ("cq1", ROOT / "assets/logo_chexquest1.png"),
    ("cq2", ROOT / "assets/logo_chexquest2.png"),
    ("cq3", ROOT / "assets/logo_chexquest3.png"),
]


def rgb332(red: int, green: int, blue: int) -> int:
    return (red >> 5 << 5) | (green >> 5 << 2) | (blue >> 6)


def emit_array(lines: list[str], declaration: str, values: list[int]) -> None:
    lines.append(f"static const unsigned char {declaration}[] = {{")
    for start in range(0, len(values), 24):
        lines.append("  " + ", ".join(f"0x{v:02x}" for v in values[start:start + 24]) + ",")
    lines.extend(["};", ""])


background_path = ROOT / "launcher.jfif"
with Image.open(background_path) as source:
    image = source.convert("RGB")
    cover = max(SIZE[0] / image.width, SIZE[1] / image.height)
    image = image.resize((round(image.width * cover), round(image.height * cover)), Image.Resampling.LANCZOS)
    left = (image.width - SIZE[0]) // 2
    top = (image.height - SIZE[1]) // 2
    image = image.crop((left, top, left + SIZE[0], top + SIZE[1]))
    # Darken for legible controls while retaining the artwork's colors.
    image = ImageEnhance.Brightness(image).enhance(0.48)
    background = [rgb332(*pixel) for pixel in image.get_flattened_data()]

lines = ["/* Generated by scripts/prepare_launcher.py; RGB332 indexed launcher art. */", "#ifndef CHEX_LAUNCHER_ART_H", "#define CHEX_LAUNCHER_ART_H", "#define LAUNCHER_BG_W 320", "#define LAUNCHER_BG_H 200", ""]
emit_array(lines, "launcher_bg", background)
for name, path in LOGOS:
    with Image.open(path) as source:
        logo = source.convert("RGBA")
        logo.thumbnail((92, 36), Image.Resampling.LANCZOS)
        width, height = logo.size
        values: list[int] = []
        for red, green, blue, alpha in logo.get_flattened_data():
            color = rgb332(red, green, blue)
            if alpha:
                color = min(255, color + 32)
            values.extend((color, alpha))
    lines.extend([f"#define LAUNCHER_LOGO_{name.upper()}_W {width}", f"#define LAUNCHER_LOGO_{name.upper()}_H {height}"])
    emit_array(lines, f"launcher_logo_{name}[{width * height}][2]", values)
lines.extend(["#endif", ""])
OUTPUT.write_text("\n".join(lines), encoding="ascii")
print(f"Wrote {OUTPUT.relative_to(ROOT)} from launcher.jfif and {len(LOGOS)} logos")
