"""Bake the Vita launcher art (background bands + game logos) as RGB332 arrays.

The launcher draws its own tiles, text and highlight on top of ``launcher_bg``,
so the bands, rules and the panel that groups the game rows are baked here: the
Vita's 320x200 pixel buffer has no alpha blending.

Run with: ``pip install pillow`` then ``python scripts/prepare_launcher.py``
"""

from pathlib import Path

from PIL import Image, ImageDraw, ImageEnhance

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "launcher_art.h"
SIZE = (320, 200)
LOGO_HEIGHT = 28
LOGO_MAX_WIDTH = 88
BRIGHTEN = 1.22

# Layout mirrored in doomgeneric_vita.c (L_HEADER_H, L_ROW_TOP, L_FOOTER_Y ...).
HEADER_H = 30
PANEL = (2, 31, 317, 175)
FOOTER_Y = 177

GOLD = (255, 198, 68)
GOLD_DIM = (150, 122, 44)
PANEL_LINE = (104, 110, 148)
BEZEL = (10, 10, 16)

LOGOS = [
    ("cq1", ROOT / "assets/logo_chexquest1.png"),
    ("cq2", ROOT / "assets/logo_chexquest2.png"),
    ("cq3", ROOT / "assets/logo_chexquest3.png"),
]


def rgb332(red: int, green: int, blue: int) -> int:
    return (red >> 5 << 5) | (green >> 5 << 2) | (blue >> 6)


def emit_array(lines: list[str], declaration: str, values: list[int]) -> None:
    lines.append(f"static const unsigned char {declaration}[] = {{")
    for start in range(0, len(values), 24):
        lines.append("  " + ", ".join(f"0x{v:02x}" for v in values[start:start + 24]) + ",")
    lines.extend(["};", ""])


def darken(image: Image.Image, box: tuple[int, int, int, int], amount: float) -> None:
    """Blend one region of the artwork towards black (no alpha on the Vita)."""
    left, top, right, bottom = box
    region = image.crop((left, top, right + 1, bottom + 1))
    black = Image.new("RGB", region.size, (0, 0, 0))
    image.paste(Image.blend(region, black, amount), (left, top))


with Image.open(ROOT / "launcher.jfif") as source:
    image = source.convert("RGB")
    cover = max(SIZE[0] / image.width, SIZE[1] / image.height)
    image = image.resize((round(image.width * cover), round(image.height * cover)), Image.Resampling.LANCZOS)
    left = (image.width - SIZE[0]) // 2
    top = (image.height - SIZE[1]) // 2
    image = image.crop((left, top, left + SIZE[0], top + SIZE[1]))
    image = ImageEnhance.Brightness(image).enhance(0.46)
    image = ImageEnhance.Color(image).enhance(0.95)

    # Bake the UI furniture: header, row panel and footer bands plus their rules.
    darken(image, (0, 0, SIZE[0] - 1, HEADER_H - 1), 0.55)
    darken(image, (0, PANEL[1], SIZE[0] - 1, PANEL[3]), 0.52)
    darken(image, (0, FOOTER_Y, SIZE[0] - 1, SIZE[1] - 1), 0.55)

    pencil = ImageDraw.Draw(image)
    pencil.rectangle(PANEL, outline=PANEL_LINE)
    pencil.line([0, HEADER_H, SIZE[0] - 1, HEADER_H], fill=GOLD)
    pencil.line([0, FOOTER_Y - 1, SIZE[0] - 1, FOOTER_Y - 1], fill=GOLD_DIM)
    pencil.rectangle([0, 0, SIZE[0] - 1, SIZE[1] - 1], outline=BEZEL)
    pencil.line([1, 1, SIZE[0] - 2, 1], fill=BEZEL)
    pencil.line([1, SIZE[1] - 2, SIZE[0] - 2, SIZE[1] - 2], fill=BEZEL)

    background = [rgb332(*pixel) for pixel in image.get_flattened_data()]

lines = [
    "/* Generated by scripts/prepare_launcher.py; RGB332 indexed launcher art. */",
    "#ifndef CHEX_LAUNCHER_ART_H",
    "#define CHEX_LAUNCHER_ART_H",
    "#define LAUNCHER_BG_W 320",
    "#define LAUNCHER_BG_H 200",
    "",
]
emit_array(lines, "launcher_bg", background)
for name, path in LOGOS:
    with Image.open(path) as source:
        logo = source.convert("RGBA")
        logo.thumbnail((LOGO_MAX_WIDTH, LOGO_HEIGHT), Image.Resampling.LANCZOS)
        width, height = logo.size
        values: list[int] = []
        for red, green, blue, alpha in logo.get_flattened_data():
            # Lift the colours before packing: brightening the packed RGB332 byte
            # overflows into the next channel and turns gold/pink logos white.
            if alpha >= 128:
                lifted = (min(255, round(channel * BRIGHTEN)) for channel in (red, green, blue))
                values.extend((rgb332(*lifted), 255))
            else:
                values.extend((0, 0))
    lines.extend([f"#define LAUNCHER_LOGO_{name.upper()}_W {width}", f"#define LAUNCHER_LOGO_{name.upper()}_H {height}"])
    emit_array(lines, f"launcher_logo_{name}", values)
lines.extend(["#endif", ""])
OUTPUT.write_text("\n".join(lines), encoding="ascii")
print(f"Wrote {OUTPUT.relative_to(ROOT)} from launcher.jfif and {len(LOGOS)} logos")
