"""Generate the launcher QR code for the game data download.

Writes two artifacts from the same matrix:

- ``assets/data_qr.png``: a standalone QR image (README / sharing).
- ``launcher_qr.h``: the module bitmap the Vita launcher draws on screen.

The QR points at the MediaFire archive that holds the free game data files
(CHEX.WAD, CHEX2.WAD, chex3v.wad, chex3.deh); it contains no copyrighted
content itself.

Run with: ``pip install qrcode pillow`` then ``python scripts/prepare_qr.py``
"""

from pathlib import Path

import qrcode
from qrcode.constants import ERROR_CORRECT_M

from PIL import Image

ROOT = Path(__file__).resolve().parents[1]
DATA_URL = "https://www.mediafire.com/file/dexl4gb4wbi0fmj/chexquestcollection.zip/file"
PNG_MODULE = 8
PNG_BORDER = 4

code = qrcode.QRCode(error_correction=ERROR_CORRECT_M, border=0, box_size=1)
code.add_data(DATA_URL)
code.make(fit=True)
matrix = code.get_matrix()
modules = len(matrix)
if modules != len(matrix[0]):
    raise SystemExit("QR matrix is not square")

# Standalone PNG with a proper quiet zone.
size = (modules + 2 * PNG_BORDER) * PNG_MODULE
image = Image.new("L", (size, size), 255)
pixels = image.load()
for y, row in enumerate(matrix):
    for x, dark in enumerate(row):
        if not dark:
            continue
        x0 = (x + PNG_BORDER) * PNG_MODULE
        y0 = (y + PNG_BORDER) * PNG_MODULE
        for py in range(y0, y0 + PNG_MODULE):
            for px in range(x0, x0 + PNG_MODULE):
                pixels[px, py] = 0
image.save(ROOT / "assets/data_qr.png", optimize=True)

lines = [
    "/* Generated by scripts/prepare_qr.py; QR code for the game data download. */",
    "#ifndef CHEX_LAUNCHER_QR_H",
    "#define CHEX_LAUNCHER_QR_H",
    f"#define LAUNCHER_QR_MODULES {modules}",
    "",
    "static const char *const launcher_qr_rows[LAUNCHER_QR_MODULES] = {",
]
for row in matrix:
    lines.append("  \"" + "".join("#" if dark else "." for dark in row) + "\",")
lines.extend(["};", "", "#endif", ""])
(ROOT / "launcher_qr.h").write_text("\n".join(lines), encoding="ascii")

print(f"{modules}x{modules} QR (error correction M) written for {DATA_URL}")
